### ISSUE TITLE
Namespacing?

### ISSUE THREAD

**Issue by CpuID** [buildkite/sockguard#39]
(assume `sockguard` is being used as a sidecar to a containerized ephemeral build agent for the below use case)

Something we have run into at least once so far: if 2 jobs fire on our CI scheduler, and it spins up 2 `docker-compose` stacks at once, they very likely end up with identical container names, and one will fail due to the container names already being in use.

Example:

`appdir_servicename_1`
`appdir_anotherservice_1`

Now, one alternative to this would be to throw a random `-p` at the `docker-compose` calls via the CI job configuration (eg. a bash snippet), but this raises the question: is this the right answer?

Should `sockguard` consider namespacing the resource names that need to be unique, eg. container name? I'm picturing a container name prefix or something as a first step here, but would likely need to expand to other resources also.

`sockguard` would then need to strip the prefix when returning results to lookup operations etc also.

@lox I'd love your 2c on this one, mostly from a "making things work reliably and transparently" without having to apply `-p` style hacks etc.

**Comment by lox** [comment]
Our docker-compose plugin generates a random prefix for docker-compose projects and it works great (https://github.com/buildkite-plugins/docker-compose-buildkite-plugin). Given you can provide it as an ENV to docker-compose (`COMPOSE_PROJECT_NAME`), I'm inclined to suggest solving it that way. I think where possible it's best to push functionality into the docker ecosystem rather than solve it in sockguard.

That said, something like `--container-prefix` would potentially be generally useful!

**Comment by CpuID** [comment]
Yep, fair call. I think documenting that caveat in the README or a use cases file or something might be worthwhile to others in future.

I think I'll stick to the project name change approach for now, thx for the feedback.
